apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-app-deployment
  labels:
    app: static-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: static-app
  template:
    metadata:
      labels:
        app: static-app
    spec:
      containers:
      - name: static-app
        image: dexteromen/static-app:latest
        ports:
        - containerPort: 80
