apiVersion: apps/v1
kind: Deployment #Specifies this is a Kubernetes Deployment resource.
metadata:
  name: notejam-app #Names the Deployment.
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notejam-app # Links the Deployment to pods with the label
  template: #Defines the pod template
    metadata: 
      labels:
        app: notejam-app # Labels pods for identification.
    spec:
      containers: #Defines the container(s) in each pod.
      - name: notejam-app
        image: dexteromen/notejam-app:latest 
        ports:
        - containerPort: 4000
        
        # these are the environment variables
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: notejam-config
              key: NODE_ENV
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: notejam-config
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: notejam-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: notejam-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: notejam-secret
              key: DB_NAME
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: notejam-secret
              key: DB_PORT
        resources:
          requests: #Minimum resources (128Mi memory, 250m CPU = 0.25 cores).
            memory: "128Mi"
            cpu: "250m"
          limits: # Maximum resources (256Mi memory, 500m CPU = 0.5 cores).
            memory: "256Mi"
            cpu: "500m"
        volumeMounts: #Mounts a volume at /app/uploads for storing uploaded files
        - mountPath: /app/uploads 
          name: appdata-volume
      volumes: #Defines a volume for the container.
      - name: appdata-volume
        emptyDir: {} #Creates a temporary, pod-specific storage (data is lost when the pod restarts).
