apiVersion: v1
kind: Service
metadata:
  name: notejam-app
spec:
  selector:
    app: notejam-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
      nodePort: 30727 
  type: NodePort
