apiVersion: v1
kind: Secret
metadata:
  name: notejam-secret
type: Opaque
data:
  DB_USER: cG9zdGdyZXM=          # Base64 encoded value of 'postgres'
  DB_PASSWORD: cGFzc3dvcmQ=      # Base64 encoded value of 'password'
  DB_NAME: bm90ZWphbQ==      # Base64 encoded value of 'notejam'
  DB_PORT: NTQzMg==          # Base64 encoded value of '5432'
